### ISSUE TITLE
Approaches to Initializing a relic db

### ISSUE THREAD

**Issue by kinleyd** [wotbrew/relic#52]
Following the exchange on the relic channel on Slack, I used both these  approaches to initialize a relic db:

{:Customer coll-of-rows}
(into [:insert :Customer] coll-of-rows)

With the first approach there were a number of problems:

(def db (rel/transact {:Customer '({:name "bob"} {:name "alice"})}))
(rel/q db [[:from :Customer]]) ; query works
(rel/transact db [:update :Customer {:name "Bob"}[= :name "bob"]]) ; bob is updated, but alice is deleted
(rel/transact db [:delete :Customer [= :name "bob"]]) ; everybody is deleted
(rel/transact db [:insert :Customer {:name "jack"}, {:name "jill"}]) ; bob and alice are deleted, jack and jill are inserted

With the second approach everything worked as expected:

(def db (rel/transact {} (into [:insert :Customer] '({:name "bob"} {:name "alice"})))) 
(rel/q db [[:from :Customer]]) ; query works
(rel/transact db [:update :Customer {:name "Bob"}[= :name "bob"]]) ; bob is updated, alice isn't deleted
(rel/transact db [:delete :Customer [= :name "bob"]]) ; only bob is deleted
(rel/transact db [:insert :Customer {:name "jack"}, {:name "jill"}]) ; bob and alice aren't deleted, jack and jill are inserted

I'm not sure why the first had those problems but I thought I'd raise the issue.

**Comment by wotbrew** [comment]
Thanks @kinleyd, at the moment you have always have to manipulate rows using transact - including insert, as that maintains & creates the relic metadata where all the magic happens. If the value of the map is out-of-sync with the relic metadata, you get glitches.

So `(rel/transact {} {:Customer rows})` in the first instance should be glitch free.

You cannot manipulate the map directly, or (right now) start with anything but an empty map.

I'll leave this open for a fix anyhow as I can see the problems this will cause!

**Comment by wotbrew** [comment]
The fix I have in mind is that transact should return a RelicDB typed map that, is a map, so I can detect drift. Been planning this for a little while. Keeps the relic graph out of meta too, can just be an internal field.

**Comment by kinleyd** [comment]
Great!

**Comment by kinleyd** [comment]
> So `(rel/transact {} {:Customer rows})` in the first instance should be glitch free.

Yes, that does work without problem. I lost a couple of hours trying to figure out why my test code wouldn't work. :)

I've been playing around with relic the last few days and am absolutely loving what it already does, so kudos to you!

I have one question at this stage:

Do you see any pitfalls if I redef a relic db in this way as I massage my data?:
(def db (rel/transact db [:delete :Customer [= :name "bob"]])
I know this isn't idiomatic, but it is convenient especially when there are a number of updates to apply to a db.

**Comment by wotbrew** [comment]
next release should contain fewer surprises like this due to #56
