### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by kinleyd** [wotbrew/relic#53]
At [https://wotbrew.github.io/relic/update/](url):

Incomplete example:
;; functions can be used
(rel/transact db [:update :Counter #(update % :n 
;; => {:Counter #{{:n 1}}}

Example appears complete but doesn't work:
;; a set map can be terser, it takes functions/relic-expressions in value position.
(rel/transact db [:update :Counter {:n inc}])
;; => {:Counter #{{:n 1}}}

**Comment by wotbrew** [comment]
Thanks for the report, I'll fix as soon as I can get to it. Second example should be `[:update :Counter {:n [inc :n]}]`

**Comment by wotbrew** [comment]
Should be fixed as soon as gh-pages updates
