### ISSUE TITLE
:join does not appear to work with the inner :select at all times

### ISSUE THREAD

**Issue by ikappaki** [wotbrew/relic#61]
Hi,

I can't seem to be able to :join when the inner :select expression does not include the joined key of the inner table.

To reproduce

1. Create a `deps.edn` file to download relic.
``` clojure
{:paths ["src"]
 :deps {com.wotbrew/relic {:mvn/version "0.1.5"}}}
```
2. Create a `src/join.clj` file to create a relic database with two tables, and :join then on the `:id` keys, attempting to only join the non-id  column of the inner table
``` clojure
(ns join
  (:require [com.wotbrew.relic :as rel]))


(def db (-> (rel/transact {} [:insert :Data
                              {:id 1 :name "bob"}
                              {:id 2 :name "alice"}])
            (rel/transact {} [:insert :Other
                              {:data-id 1 :prop "xyz"}
                              {:data-id 2 :prop "abc"}])))

(rel/q db [[:from :Data]
           [:join [[:from :Other] [:select :prop]] {:id :data-id}]])
;; => nil
```
3. No entries are returned, though the join keys match. I was expecting to see the two `:Data` rows with the addition of the `:prop` column.

If we were not to include the `:select` clause in the inner join, or explicitly mention the inner key in the select, then it works, though it now includes an undesired (for this example) :data-id column
```clojure
(rel/q db [[:from :Data]
           [:join [[:from :Other] [:select :data-id :prop]] {:id :data-id}]])
;; ({:id 1, :name "bob", :data-id 1, :prop "xyz"}
;;  {:id 2, :name "alice", :data-id 2, :prop "abc"}
```

Or it is possible that I've got the :join operation wrong? Now that I think about it, I was expecting

1. The two tables (`:Data` and `:Other`) are joined first based on the keys, then :select in the inner table specifies which columns to include from the inner table.
2. but it could as well be that he inner :join expression is evaluated first and then the result is joined as per the keys matching requirements?

Thanks

**Comment by wotbrew** [comment]
> but it could as well be that he inner :join expression is evaluated first and then the result is joined as per the keys matching requirements?

Ya got it.

The val (right) expressions in the Equijoin map see the materialized rows from the inner query, so in this case `:data-id` needs to be part of the selection.

Closing but feel free to re-open if I've missed something else, thanks so much 🙏

**Comment by ikappaki** [comment]
Thanks @wotbrew,

> The val (right) expressions in the Equijoin map see the materialized rows from the inner query, so in this case `:data-id` needs to be part of the selection.
> 

Do you mind if I submit a PR to update the doc entry with an example?

Also, I don't think I understand why the `clause` is referred to as `expr`, isn't this supposed to be only column keywords from the coresponding outer/inner queries? and what does the `more` part mean, more `clause`s?

> Like `set/join`, clause is a map of expressions on the left to expressions on the right.
> ...
> ```clojure 
> join = [:join right clause & more]
> right = query | table
> clause = {left-expr right-expr, ...}
> ```

Thanks

**Comment by wotbrew** [comment]
Sure please submit a PR, 👍 .

IIRC join predicate 'clause's take expressions, not only keywords. The `more` is because you can supply multiple 'right' relation and clause maps so you could do something like `[:join :a {:a :a} :b {:b :b}]`. Relic joins are always binary so this is only a bit of sugar. 

Hope that makes sense!

Thanks so much for trying it out and opening these issues @ikappaki 🙏 .

**Comment by wotbrew** [comment]
Doc brevity is a major problem, could spend a few more days on the docs! My brain is on other projects, but I hope to get some time with Relic soon.
